name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          # Required for SonarQube to see code history
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Package
        # -f points Maven to the correct subdirectory 'sonarqube'
        run: |
          mvn clean verify \
            -f sonarqube/pom.xml \
            -DskipTests \
            -Dcheckstyle.skip=true

      - name: Run SonarQube analysis
        run: |
          mvn sonar:sonar \
            -f sonarqube/pom.xml \
            -Dsonar.projectKey=Test-Project-Bala \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dcheckstyle.skip=true
