name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Maven Wrapper Executable
        # This targets the subfolder where your mvnw file lives
        run: chmod +x ./spring-petclinic/mvnw

      - name: Build and Package
        # Run inside the subfolder to find pom.xml
        run: ./mvnw clean verify -DskipTests
        working-directory: ./spring-petclinic

      - name: Run SonarQube analysis
        # Run inside the subfolder to find pom.xml
        run: ./mvnw sonar:sonar \
          -Dsonar.projectKey=Test-Project-Bala \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -DskipTests
        working-directory: ./spring-petclinic
